parameters:
  thinframe.server.port: 1337
  thinframe.server.host: '127.0.0.1'

services:
  thinframe.server.react.event_loop:
    class: 'React\EventLoop\LoopInterface'
    factory_class: 'React\EventLoop\Factory'
    factory_method: 'create'

  thinframe.server.react.socket_server:
    class: 'React\Socket\Server'
    arguments: ['@thinframe.server.react.event_loop']

  thinframe.server.react.http_server:
    class: 'React\Http\Server'
    arguments: ['@thinframe.server.react.socket_server']

  thinframe.server.react.request_listener:
    class: 'ThinFrame\Server\RequestListener'
    tags:
        - { name:'thinframe.events.listener' }

  thinframe.server:
    class: 'ThinFrame\Server\HttpServer'
    arguments: ['%thinframe.server.port%','%thinframe.server.host%']
    calls:
        - ['setEventLoop', ['@thinframe.server.react.event_loop']]
        - ['setSocketServer',['@thinframe.server.react.socket_server']]
        - ['setHttpServer', ['@thinframe.server.react.http_server']]
