services:
  thinframe.server.react.event_loop:
    class: 'React\EventLoop\LoopInterface'
    factory_class: 'React\EventLoop\Factory'
    factory_method: 'create'

  thinframe.server.react.socket_server:
    class: 'React\Socket\Server'
    arguments: ['@thinframe.server.react.event_loop']

  thinframe.server.react.http_server:
    class: 'React\Http\Server'
    arguments: ['@thinframe.server.react.socket_server']

  thinframe.server.listeners.request:
    class: 'ThinFrame\Server\Listeners\RequestListener'
    tags:
        - { name:'thinframe.events.listener' }

  thinframe.server:
    class: 'ThinFrame\Server\Server'
    calls:
        - ['setEventLoop', ['@thinframe.server.react.event_loop']]
        - ['setSocketServer',['@thinframe.server.react.socket_server']]
        - ['setHttpServer', ['@thinframe.server.react.http_server']]
