services:
  server.react.event_loop:
    class: 'React\EventLoop\LoopInterface'
    factory_class: 'React\EventLoop\Factory'
    factory_method: 'create'

  server.react.socket_server:
    class: 'React\Socket\Server'
    arguments: ['@server.react.event_loop']

  server.react.http_server:
    class: 'React\Http\Server'
    arguments: ['@server.react.socket_server']

  server.listeners.request:
    class: 'ThinFrame\Server\Listeners\RequestListener'
    tags:
        - { name: 'events.listener'}

  server:
    class: 'ThinFrame\Server\Server'
    calls:
        - ['setEventLoop', ['@server.react.event_loop']]
        - ['setSocketServer',['@server.react.socket_server']]
        - ['setHttpServer', ['@server.react.http_server']]
